### ISSUE TITLE
Wheel

### ISSUE THREAD

**Issue by pvizeli** [rishatik92/ya_ma#1]
We can't build wheel with this packages because the manifest of license not exists.

`pip wheel ya-ma==0.3.4`

I exclude it now from HA.

**Comment by rishatik92** [comment]
Hi
Need to add it to the tar.gz?

**Comment by rishatik92** [comment]
> We can't build wheel with this packages because the manifest of license not exists.
> 
> `pip wheel ya-ma==0.3.4`
> 
> I exclude it now from HA.

ya-ma 0.3.7 - can you check please this version?

**Comment by pvizeli** [comment]
Sure

**Comment by pvizeli** [comment]
Yep, work perfect
